# This is the config that's used as a fallback when a field is missing from the user's config.toml.

bind = "0.0.0.0:28019"

engine_list_separator = false
version_info = false

[engines]
google = { weight = 1.05 }
bing = { weight = 1.0 }
brave = { weight = 1.25 }

google_scholar = { enabled = false, weight = 0.50 }
rightdao = { enabled = false, weight = 0.10 }
stract = { enabled = false, weight = 0.15 }
yep = { enabled = false, weight = 0.10 }

# calculators (give them a high weight so they're always the first thing in autocomplete)
numbat = { weight = 10 }
fend = { enabled = false, weight = 10 }

[engines.marginalia]
args = { profile = "corpo", js = "default", adtech = "default" }
weight = 0.15

[engines.mdn]
# the number of sections of text to display
# 1 is just the summary and 0 is no limit
max_sections = 1
