# See src/config.rs for all of the possible options

bind = "0.0.0.0:28019"
api = false

[ui]
# engine_list_separator = true
# show_version_info = true
# stylesheet_url = "/themes/catppuccin-mocha.css"

[engines]
# numbat = false
# fend = true
